apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "dynamic-cluster-config"
  environment:
    cluster_type: ec2
    domain: pet.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: staging
    grafana_obs_api: https://grafana.central-otlp.pet.platform.vee.codes
    public_ip: 98.82.37.17
  annotations:
    github.com/project-slug: veecode-homolog/dynamic-cluster-config
    infracost/project: dynamic-cluster-config
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,infracost.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$98.82.37.17 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$98.82.37.17:~/.kube/config ~/.kube/config-dynamic-cluster-config\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"98.82.37.17\")' -i ~/.kube/config-dynamic-cluster-config\n  export KUBECONFIG=~/.kube/config-dynamic-cluster-config\n  kubectl get pods -A\n"
    kubernetes.io/secret-name: 'cluster-hml-ec2-secret'
    kubernetes.io/secret-namespace: 'veecode-homolog'
    kubernetes.io/auth-provider: 'custom'
    kubernetes.io/api-server: "https://34.192.236.45:6550"
    kubernetes.io/skip-tls-verify: "true"
    kubernetes.io/skip-metrics-lookup: "false"    
    veecode/cluster-name: "cluster-hml-ec2"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/pet-environment-homolog'
