apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "dynamic-cluster-config"
  environment:
    cluster_type: ec2
    domain: pet.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: staging
    grafana_obs_api: https://grafana.central-otlp.pet.platform.vee.codes
  annotations:
    github.com/project-slug: veecode-homolog/dynamic-cluster-config
    infracost/project: dynamic-cluster-config
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,infracost.yml
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/pet-environment-homolog'
